package main

import (
	"log"
	"net/http"

	"golang.org/x/net/http2"
	"golang.org/x/net/http2/h2c"

	todov1connect "grpc_todo/gen/todo/v1/todov1connect"
	internal "grpc_todo/internal/server"
	// generated by protoc-gen-connect-go
)

func main() {
    todo := &internal.ToDoServer{}
    mux := http.NewServeMux()
    path, handler := todov1connect.NewToDoServiceHandler(todo)
    mux.Handle(path, handler)
    log.Println("Server start")
    http.ListenAndServe(
        "localhost:8080",
        // Use h2c so we can serve HTTP/2 without TLS.
        h2c.NewHandler(mux, &http2.Server{}),
    )
}